blog/urls.py
from django.urls import path
from . import views
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from blog import views
app_name='blog'

urlpatterns = [
    path("", views.all_blogs, name='all_blogs'),
    path("<int:blog_id>/", views.detail, name='detail'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name='home'),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.

class Blog(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date = models.DateField()

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)
    
    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
import random
from .models import Blog

# Create your views here.
def all_blogs(request):
    blogs = Blog.objects.order_by('-date')
    return render(request, 'blog/all_blogs.html', {'blogs':blogs})
    
def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog':blog})
# def about(request):
#     return render(request, 'generator/about.html')

portfolio/views.py
from django.shortcuts import render
from django.http import HttpResponse
import random
from .models import Project

# Create your views here.
def home(request):
    projects = Project.objects.all()
    return render(request, 'web/home.html', {'projects':projects})

# def about(request):
#     return render(request, 'generator/about.html')

blog/templates/blog/all_blogs.html
{% extends 'web/layout.html'%}

{% block content %}

<div class="container text-center">
  <h1>Blog page</h1>
</div>

<h2>Ahat has written {{ blogs.count }} blog{{ blogs.count|pluralize }}</h2>

{% for blog in blogs %}
<a href="{% url 'blog:detail' blog.id %}"><h1>{{ blog.title }}</h1></a>
<h5>{{ blog.date|date:'d M Y' }}</h5>
<p>{{ blog.description|striptags|truncatechars:100 }}</p>

{% endfor %}
{% endblock %}

blog/templates/blog/detail.html
{% extends 'web/layout.html'%}

{% block content %}

<h1>{{ blog.title }}</h1>
<h2>--{{ blog.date|date:'F jS Y' }}--</h2>
<h5>{{ blog.description }}</h5>

{% endblock %}

portfolio/templates/web/home.html
{% extends 'web/layout.html'%}

{% block content %}

    <h1>Ahat's portfolio</h1>

    {% load static %}
    <br>
    <a href="{% url 'blog:all_blogs' %}">All blogs</a>
    <br>
    <img src="{% static 'portfolio/IMG_5544.jpg' %}" height="800" width="600">
    <h3>ABCDEFU
    </h3>
    {% for project in projects %}
    
    <h2>{{ project.title }}</h2>
    <p>{{ project.description }}</p>
    <img src="{{ project.image.url }}" height="350" width="350">
    
    {% if project.url %}
    <br><a href="{{ project.url }}">Link</a>
    {% endif %}
    {% endfor %}
    {% endblock %}

portfolio/templates/web/layout.html
<!doctype HTML>
{% load static %}

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300&display=swap" rel="stylesheet">
    
        <link rel="stylesheet" href="{% static 'portfolio/custom.css'}">
        <link rel="icon" type="image/png" href="{% static 'portfolio/123.png'}">
        <title>Portfolio</title>
    </head>

<body>
<header>
  <!-- Fixed navbar -->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Ahat's portfolio</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
            <a class="nav-link" aria-current="page" href="/static/portfolio/Resume_Ahat.pdf">Resume</a>
          </li></ul>

          <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item">
                <a class="nav-link" aria-current="page" href="https://www.linkedin.com/in/ahatoz/">LinkedIn</a>
              </li></ul>

        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="" aria-label="All blogs">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
  </nav>
</header>
        <!-- Begin page content -->
<main class="flex-shrink-0">
  <div class="container">
    {% block content %} {% endblock %}
  </div>
</main>

<footer class="footer mt-auto py-3 bg-light">
  <div class="container">
    <p class="text-muted">&copy; 2022 portfolio.</p>
  </div>
</footer>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
    </body>
</html>
            

portfolio/templates/web/test.html
<!-- <!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'portfolio/custom.css'}">
    <link rel="icon" type="image/png" href="{% static 'portfolio/123.png'}">
    
    <title>Portfolio</title>

  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Dropdown
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" aria-disabled="true">Disabled</a>
            </li>
          </ul>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>
    {% block content %} {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </body>
</html> -->